### ISSUE TITLE
Is project still maintained?

### ISSUE THREAD

**Issue by heyallan** [paypal/rest-api-sample-app-nodejs#5]
Whole year since last commit.
How likely is this repo to keep up to date?

**Comment by jaypatel512** [comment]
Hey @heyallan !

We generally keep the sample app generic to our implementation. The cases that we are covering in this sample app is related to Payment APIs, that gets you started with the SDK. And generally we dont break any backward compatibility in our SDKs unless a major release, there is not much to change in this sample. 

However, if you are trying out the sample, and you see any place for improvements, definitely feel free to either ping us, or help us adding more to the sample.

**Comment by heyallan** [comment]
(Y)
